import React from 'react'
import './carousel.css'
import AliceCarousel from 'react-alice-carousel';
import 'react-alice-carousel/lib/alice-carousel.css';
const AboutCarousel = () => {


  const handleDragStart = (e) => e.preventDefault()

  const items = [
    <div onDragStart={handleDragStart} className='carousel_item w-[90%] bg-yellow-500 h-[15rem] lg:w-[70%] m-auto overflow-y-scroll lg:h-[10rem] flex items-center justify-center text-center'><p className='leading-[1.44rem]'>Home—there’s no place like it. It’s where your memories are. Where you raised your family and where friends have gathered for life’s celebrations. It’s been your basecamp through good times and bad. And it’s where you want to stay. At Right at Home, our intention is to help you do just that. Why? Because we exist to be your guide to living successfully at home, wherever home may be. It’s our purpose. Aging, disability, illness or injury can make living at home a challenge. We believe that no one should have to face the long list of complex decisions and unforeseen changes alone. We are experts, providing not just care, but coaching and experience to help navigate every step of the journey. Right at Home’s trained caregivers are passionate about helping clients because they know with each life they impact, they are changing the world.</p></div>,
    <div onDragStart={handleDragStart} className='carousel_item w-[90%] bg-yellow-500 h-[15rem] lg:w-[70%] m-auto overflow-y-scroll lg:h-[10rem] flex items-center justify-center text-center'><p className='leading-[1.44rem]'>Home—there’s no place like it. It’s where your memories are. Where you raised your family and where friends have gathered for life’s celebrations. It’s been your basecamp through good times and bad. And it’s where you want to stay. At Right at Home, our intention is to help you do just that. Why? Because we exist to be your guide to living successfully at home, wherever home may be. It’s our purpose. Aging, disability, illness or injury can make living at home a challenge. We believe that no one should have to face the long list of complex decisions and unforeseen changes alone. We are experts, providing not just care, but coaching and experience to help navigate every step of the journey. Right at Home’s trained caregivers are passionate about helping clients because they know with each life they impact, they are changing the world.</p></div>,
    <div onDragStart={handleDragStart} className='carousel_item w-[90%] bg-yellow-500 h-[15rem] lg:w-[70%] m-auto overflow-y-scroll lg:h-[10rem] flex items-center justify-center text-center'><p className='leading-[1.44rem]'>Home—there’s no place like it. It’s where your memories are. Where you raised your family and where friends have gathered for life’s celebrations. It’s been your basecamp through good times and bad. And it’s where you want to stay. At Right at Home, our intention is to help you do just that. Why? Because we exist to be your guide to living successfully at home, wherever home may be. It’s our purpose. Aging, disability, illness or injury can make living at home a challenge. We believe that no one should have to face the long list of complex decisions and unforeseen changes alone. We are experts, providing not just care, but coaching and experience to help navigate every step of the journey. Right at Home’s trained caregivers are passionate about helping clients because they know with each life they impact, they are changing the world.</p></div>,
    <div onDragStart={handleDragStart} className='carousel_item w-[90%] bg-yellow-500 h-[15rem] lg:w-[70%] m-auto overflow-y-scroll lg:h-[10rem] flex items-center justify-center text-center'><p className='leading-[1.44rem]'>Home—there’s no place like it. It’s where your memories are. Where you raised your family and where friends have gathered for life’s celebrations. It’s been your basecamp through good times and bad. And it’s where you want to stay. At Right at Home, our intention is to help you do just that. Why? Because we exist to be your guide to living successfully at home, wherever home may be. It’s our purpose. Aging, disability, illness or injury can make living at home a challenge. We believe that no one should have to face the long list of complex decisions and unforeseen changes alone. We are experts, providing not just care, but coaching and experience to help navigate every step of the journey. Right at Home’s trained caregivers are passionate about helping clients because they know with each life they impact, they are changing the world.</p></div>,
  ];

  return (

   <AliceCarousel disableButtonsControls className='m-auto w-full h-full bg-gray-500' items={items}/>

  )
}

export default AboutCarousel