export {default as Header} from './Header/Header'
export {default as Services} from './Services/Services'
export {default as About} from './About/About'
export {default as Articles} from './Articles/Articles'
export {default as What_We_Do} from './What_We_Do/What_We_Do'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'